### ISSUE TITLE
Refractor Shapes Assignment

### ISSUE THREAD

**Issue by MatthewL1515** [MatthewL1515/ShapesSketch.github.io#1]
@mrjloswald-avenues 

Assignment Page:
https://avenues.instructure.com/courses/7407/assignments/120629

I can replace values like positions, colors, and dimensions with variables to consolidate the code using variables.  This will allow easier adjustments to the rocket's size, position, and design. I did need to create more space to add the variables, but it makes viewing the drawing code much simpler for myself.

**Comment by mrjloswald-avenues** [comment]
A better use of variables would be for the bare numbers (250, 150) in your `esb` function. Also, you should rename this function to something like `rocket`.
